var arti_words_blockchain = [
    {
        "text":"blockchain",
        "size":29
    },
    {
        "text":"bitcoin",
        "size":24
    },
    {
        "text":"crypto",
        "size":23
    },
    {
        "text":"one",
        "size":20
    },
    {
        "text":"new",
        "size":20
    },
    {
        "text":"puerto",
        "size":15
    },
    {
        "text":"women",
        "size":14
    },
    {
        "text":"people",
        "size":13
    },
    {
        "text":"cryptocurrency",
        "size":13
    },
    {
        "text":"technology",
        "size":12
    },
    {
        "text":"industry",
        "size":11
    },
    {
        "text":"rico",
        "size":11
    },
    {
        "text":"tax",
        "size":11
    },
    {
        "text":"pierce",
        "size":11
    },
    {
        "text":"just",
        "size":10
    },
    {
        "text":"money",
        "size":10
    },
    {
        "text":"company",
        "size":10
    },
    {
        "text":"early",
        "size":9
    },
    {
        "text":"men",
        "size":9
    },
    {
        "text":"group",
        "size":9
    },
    {
        "text":"think",
        "size":8
    },
    {
        "text":"world",
        "size":8
    },
    {
        "text":"market",
        "size":8
    },
    {
        "text":"virtual",
        "size":8
    },
    {
        "text":"want",
        "size":8
    },
    {
        "text":"trying",
        "size":8
    },
    {
        "text":"old",
        "size":7
    },
    {
        "text":"many",
        "size":7
    },
    {
        "text":"currency",
        "size":7
    },
    {
        "text":"theres",
        "size":7
    },
    {
        "text":"quorum",
        "size":7
    },
    {
        "text":"san",
        "size":7
    },
    {
        "text":"conference",
        "size":7
    },
    {
        "text":"island",
        "size":7
    },
    {
        "text":"business",
        "size":7
    },
    {
        "text":"tech",
        "size":7
    },
    {
        "text":"great",
        "size":7
    },
    {
        "text":"make",
        "size":7
    },
    {
        "text":"last",
        "size":7
    },
    {
        "text":"taxes",
        "size":7
    },
    {
        "text":"take",
        "size":7
    },
    {
        "text":"create",
        "size":7
    },
    {
        "text":"told",
        "size":6
    },
    {
        "text":"year",
        "size":6
    },
    {
        "text":"dont",
        "size":6
    },
    {
        "text":"time",
        "size":6
    },
    {
        "text":"cryptocurrencies",
        "size":6
    },
    {
        "text":"back",
        "size":6
    },
    {
        "text":"levin",
        "size":6
    },
    {
        "text":"long",
        "size":6
    },
    {
        "text":"investors",
        "size":6
    },
    {
        "text":"going",
        "size":6
    },
    {
        "text":"currencies",
        "size":6
    },
    {
        "text":"two",
        "size":6
    },
    {
        "text":"juan",
        "size":6
    },
    {
        "text":"week",
        "size":6
    },
    {
        "text":"banks",
        "size":6
    },
    {
        "text":"startup",
        "size":5
    },
    {
        "text":"cash",
        "size":5
    },
    {
        "text":"say",
        "size":5
    },
    {
        "text":"announced",
        "size":5
    },
    {
        "text":"price",
        "size":5
    },
    {
        "text":"made",
        "size":5
    },
    {
        "text":"still",
        "size":5
    },
    {
        "text":"offering",
        "size":5
    },
    {
        "text":"bank",
        "size":5
    },
    {
        "text":"collins",
        "size":5
    },
    {
        "text":"get",
        "size":5
    },
    {
        "text":"puertopia",
        "size":5
    },
    {
        "text":"times",
        "size":5
    },
    {
        "text":"value",
        "size":5
    },
    {
        "text":"im",
        "size":5
    },
    {
        "text":"look",
        "size":5
    },
    {
        "text":"security",
        "size":5
    },
    {
        "text":"know",
        "size":5
    },
    {
        "text":"digital",
        "size":5
    },
    {
        "text":"big",
        "size":5
    },
    {
        "text":"days",
        "size":5
    },
    {
        "text":"york",
        "size":5
    },
    {
        "text":"another",
        "size":5
    },
    {
        "text":"city",
        "size":5
    },
    {
        "text":"figure",
        "size":5
    },
    {
        "text":"billion",
        "size":5
    },
    {
        "text":"million",
        "size":4
    },
    {
        "text":"gold",
        "size":4
    },
    {
        "text":"see",
        "size":4
    },
    {
        "text":"much",
        "size":4
    },
    {
        "text":"puertopians",
        "size":4
    },
    {
        "text":"coin",
        "size":4
    },
    {
        "text":"initial",
        "size":4
    },
    {
        "text":"read",
        "size":4
    },
    {
        "text":"referring",
        "size":4
    },
    {
        "text":"around",
        "size":4
    },
    {
        "text":"enough",
        "size":4
    },
    {
        "text":"point",
        "size":4
    },
    {
        "text":"first",
        "size":4
    },
    {
        "text":"investment",
        "size":4
    },
    {
        "text":"american",
        "size":4
    },
    {
        "text":"already",
        "size":4
    },
    {
        "text":"nygard",
        "size":4
    },
    {
        "text":"little",
        "size":4
    },
    {
        "text":"among",
        "size":4
    },
    {
        "text":"billions",
        "size":4
    },
    {
        "text":"gender",
        "size":4
    },
    {
        "text":"financial",
        "size":4
    },
    {
        "text":"lot",
        "size":4
    },
    {
        "text":"theyre",
        "size":4
    },
    {
        "text":"hurricane",
        "size":4
    },
    {
        "text":"day",
        "size":4
    },
    {
        "text":"others",
        "size":4
    },
    {
        "text":"build",
        "size":4
    },
    {
        "text":"larkin",
        "size":4
    },
    {
        "text":"culture",
        "size":4
    },
    {
        "text":"tree",
        "size":4
    },
    {
        "text":"state",
        "size":4
    },
    {
        "text":"buy",
        "size":4
    },
    {
        "text":"open",
        "size":4
    },
    {
        "text":"worth",
        "size":4
    },
    {
        "text":"tulip",
        "size":4
    },
    {
        "text":"minor",
        "size":4
    },
    {
        "text":"computer",
        "size":4
    },
    {
        "text":"tokens",
        "size":4
    },
    {
        "text":"got",
        "size":4
    },
    {
        "text":"known",
        "size":4
    },
    {
        "text":"trump",
        "size":4
    },
    {
        "text":"us",
        "size":4
    },
    {
        "text":"month",
        "size":4
    },
    {
        "text":"building",
        "size":4
    },
    {
        "text":"held",
        "size":3
    },
    {
        "text":"rush",
        "size":3
    },
    {
        "text":"even",
        "size":3
    },
    {
        "text":"means",
        "size":3
    },
    {
        "text":"maria",
        "size":3
    },
    {
        "text":"working",
        "size":3
    },
    {
        "text":"felt",
        "size":3
    },
    {
        "text":"speculation",
        "size":3
    },
    {
        "text":"using",
        "size":3
    },
    {
        "text":"happened",
        "size":3
    },
    {
        "text":"america",
        "size":3
    },
    {
        "text":"town",
        "size":3
    },
    {
        "text":"magazine",
        "size":3
    },
    {
        "text":"question",
        "size":3
    },
    {
        "text":"miami",
        "size":3
    },
    {
        "text":"party",
        "size":3
    },
    {
        "text":"event",
        "size":3
    },
    {
        "text":"moved",
        "size":3
    },
    {
        "text":"whose",
        "size":3
    },
    {
        "text":"seen",
        "size":3
    },
    {
        "text":"sources",
        "size":3
    },
    {
        "text":"making",
        "size":3
    },
    {
        "text":"move",
        "size":3
    },
    {
        "text":"outstanding",
        "size":3
    },
    {
        "text":"call",
        "size":3
    },
    {
        "text":"wearing",
        "size":3
    },
    {
        "text":"actually",
        "size":3
    },
    {
        "text":"future",
        "size":3
    },
    {
        "text":"start",
        "size":3
    },
    {
        "text":"executive",
        "size":3
    },
    {
        "text":"full",
        "size":3
    },
    {
        "text":"speakers",
        "size":3
    },
    {
        "text":"also",
        "size":3
    },
    {
        "text":"hes",
        "size":3
    },
    {
        "text":"strip",
        "size":3
    },
    {
        "text":"ledger",
        "size":3
    },
    {
        "text":"left",
        "size":3
    },
    {
        "text":"maybe",
        "size":3
    },
    {
        "text":"almost",
        "size":3
    },
    {
        "text":"baldet",
        "size":3
    },
    {
        "text":"recent",
        "size":3
    },
    {
        "text":"percent",
        "size":3
    },
    {
        "text":"events",
        "size":3
    },
    {
        "text":"venture",
        "size":3
    },
    {
        "text":"firm",
        "size":3
    },
    {
        "text":"interest",
        "size":3
    },
    {
        "text":"beyond",
        "size":3
    },
    {
        "text":"morris",
        "size":3
    },
    {
        "text":"former",
        "size":3
    },
    {
        "text":"runs",
        "size":3
    },
    {
        "text":"thats",
        "size":3
    },
    {
        "text":"conferences",
        "size":3
    },
    {
        "text":"anyone",
        "size":3
    },
    {
        "text":"commerce",
        "size":3
    },
    {
        "text":"clemenson",
        "size":3
    },
    {
        "text":"change",
        "size":3
    },
    {
        "text":"says",
        "size":3
    },
    {
        "text":"experiment",
        "size":3
    },
    {
        "text":"amazon",
        "size":3
    },
    {
        "text":"apple",
        "size":3
    },
    {
        "text":"funded",
        "size":3
    },
    {
        "text":"boom",
        "size":3
    },
    {
        "text":"bubble",
        "size":3
    },
    {
        "text":"graber",
        "size":3
    },
    {
        "text":"name",
        "size":3
    },
    {
        "text":"youre",
        "size":3
    },
    {
        "text":"ad",
        "size":3
    },
    {
        "text":"chief",
        "size":3
    },
    {
        "text":"historic",
        "size":3
    },
    {
        "text":"need",
        "size":3
    },
    {
        "text":"economy",
        "size":3
    },
    {
        "text":"tried",
        "size":3
    },
    {
        "text":"local",
        "size":3
    },
    {
        "text":"tea",
        "size":3
    },
    {
        "text":"site",
        "size":3
    },
    {
        "text":"built",
        "size":3
    },
    {
        "text":"weeks",
        "size":3
    },
    {
        "text":"news",
        "size":3
    },
    {
        "text":"models",
        "size":3
    },
    {
        "text":"recently",
        "size":3
    },
    {
        "text":"development",
        "size":3
    },
    {
        "text":"entrepreneurs",
        "size":3
    },
    {
        "text":"system",
        "size":3
    },
    {
        "text":"club",
        "size":3
    },
    {
        "text":"man",
        "size":3
    },
    {
        "text":"invest",
        "size":3
    },
    {
        "text":"iced",
        "size":3
    },
    {
        "text":"investor",
        "size":3
    },
    {
        "text":"began",
        "size":3
    },
    {
        "text":"sold",
        "size":3
    },
    {
        "text":"lopez",
        "size":3
    },
    {
        "text":"diversity",
        "size":3
    },
    {
        "text":"rill",
        "size":2
    },
    {
        "text":"needed",
        "size":2
    },
    {
        "text":"harper",
        "size":2
    },
    {
        "text":"ethereum",
        "size":2
    },
    {
        "text":"locations",
        "size":2
    }
]
