var co_occur_trump_NYT = [
    {
        "text":"[cohen,lawyer]",
        "size":105
    },
    {
        "text":"[trump,donald]",
        "size":104
    },
    {
        "text":"[trump,organization]",
        "size":100
    },
    {
        "text":"[cohen,trumps]",
        "size":99
    },
    {
        "text":"[president,trumps]",
        "size":95
    },
    {
        "text":"[cohen,michael]",
        "size":95
    },
    {
        "text":"[cohen,president]",
        "size":74
    },
    {
        "text":"[daniels,stormy]",
        "size":74
    },
    {
        "text":"[michael,cohen]",
        "size":73
    },
    {
        "text":"[president,donald]",
        "size":70
    }
]
