var arti_words_trump = [
    {
        "text":"trump",
        "size":335
    },
    {
        "text":"president",
        "size":207
    },
    {
        "text":"stormy",
        "size":195
    },
    {
        "text":"cohen",
        "size":108
    },
    {
        "text":"lawyer",
        "size":100
    },
    {
        "text":"daniels",
        "size":96
    },
    {
        "text":"ms",
        "size":89
    },
    {
        "text":"donald",
        "size":88
    },
    {
        "text":"michael",
        "size":78
    },
    {
        "text":"clifford",
        "size":77
    },
    {
        "text":"trumps",
        "size":71
    },
    {
        "text":"called",
        "size":71
    },
    {
        "text":"sexual",
        "size":70
    },
    {
        "text":"stormy",
        "size":70
    },
    {
        "text":"question",
        "size":68
    },
    {
        "text":"suing",
        "size":66
    },
    {
        "text":"encounter",
        "size":65
    },
    {
        "text":"claim",
        "size":64
    },
    {
        "text":"defamation",
        "size":62
    },
    {
        "text":"trump s",
        "size":54
    },
    {
        "text":"company",
        "size":50
    },
    {
        "text":"interview",
        "size":49
    },
    {
        "text":"organization",
        "size":45
    },
    {
        "text":"house",
        "size":44
    },
    {
        "text":"last",
        "size":42
    },
    {
        "text":"campaign",
        "size":42
    },
    {
        "text":"made",
        "size":41
    },
    {
        "text":"business",
        "size":41
    },
    {
        "text":"oil",
        "size":40
    },
    {
        "text":"white",
        "size":40
    },
    {
        "text":"also",
        "size":38
    },
    {
        "text":"trucks",
        "size":37
    },
    {
        "text":"companies",
        "size":36
    },
    {
        "text":"india",
        "size":35
    },
    {
        "text":"one",
        "size":35
    },
    {
        "text":"offshore",
        "size":34
    },
    {
        "text":"safety",
        "size":33
    },
    {
        "text":"according",
        "size":33
    },
    {
        "text":"affair",
        "size":32
    },
    {
        "text":"whether",
        "size":32
    },
    {
        "text":"agreement",
        "size":32
    },
    {
        "text":"industry",
        "size":32
    },
    {
        "text":"like",
        "size":32
    },
    {
        "text":2016,
        "size":31
    },
    {
        "text":"fitzgerald",
        "size":31
    },
    {
        "text":"payment",
        "size":30
    },
    {
        "text":"gas",
        "size":29
    },
    {
        "text":"year",
        "size":29
    },
    {
        "text":"former",
        "size":28
    },
    {
        "text":"signed",
        "size":28
    },
    {
        "text":"time",
        "size":28
    },
    {
        "text":"mueller",
        "size":27
    },
    {
        "text":"people",
        "size":27
    },
    {
        "text":"federal",
        "size":27
    },
    {
        "text":"administration",
        "size":27
    },
    {
        "text":"will",
        "size":26
    },
    {
        "text":"now",
        "size":26
    },
    {
        "text":"even",
        "size":25
    },
    {
        "text":"say",
        "size":25
    },
    {
        "text":"election",
        "size":24
    },
    {
        "text":"platforms",
        "size":23
    },
    {
        "text":"way",
        "size":23
    },
    {
        "text":"statement",
        "size":22
    },
    {
        "text":"public",
        "size":22
    },
    {
        "text":"angelle",
        "size":22
    },
    {
        "text":"just",
        "size":22
    },
    {
        "text":"name",
        "size":22
    },
    {
        "text":"special",
        "size":21
    },
    {
        "text":"president s",
        "size":21
    },
    {
        "text":"many",
        "size":21
    },
    {
        "text":"two",
        "size":21
    },
    {
        "text":"government",
        "size":21
    },
    {
        "text":"agency",
        "size":21
    },
    {
        "text":"united",
        "size":21
    },
    {
        "text":"filed",
        "size":21
    },
    {
        "text":"counsel",
        "size":21
    },
    {
        "text":"including",
        "size":21
    },
    {
        "text":"million",
        "size":20
    },
    {
        "text":"gulf",
        "size":20
    },
    {
        "text":"fintiklis",
        "size":20
    },
    {
        "text":"times",
        "size":20
    },
    {
        "text":"can",
        "size":20
    },
    {
        "text":"relationship",
        "size":20
    },
    {
        "text":"first",
        "size":20
    },
    {
        "text":"told",
        "size":19
    },
    {
        "text":"energy",
        "size":19
    },
    {
        "text":"story",
        "size":19
    },
    {
        "text":"help",
        "size":19
    },
    {
        "text":"glider",
        "size":18
    },
    {
        "text":"whose",
        "size":18
    },
    {
        "text":"american",
        "size":18
    },
    {
        "text":"clear",
        "size":18
    },
    {
        "text":"presidential",
        "size":18
    },
    {
        "text":"legal",
        "size":18
    },
    {
        "text":"department",
        "size":18
    },
    {
        "text":"alleged",
        "size":18
    },
    {
        "text":"get",
        "size":17
    },
    {
        "text":"records",
        "size":17
    },
    {
        "text":"lawsuit",
        "size":17
    },
    {
        "text":"washington",
        "size":17
    },
    {
        "text":"russia",
        "size":17
    },
    {
        "text":"office",
        "size":16
    },
    {
        "text":"may",
        "size":16
    },
    {
        "text":"keep",
        "size":16
    },
    {
        "text":"questions",
        "size":16
    },
    {
        "text":"documents",
        "size":16
    },
    {
        "text":"week",
        "size":16
    },
    {
        "text":"well",
        "size":16
    },
    {
        "text":130000,
        "size":16
    },
    {
        "text":"political",
        "size":16
    },
    {
        "text":"impeachment",
        "size":16
    },
    {
        "text":"drilling",
        "size":16
    },
    {
        "text":"money",
        "size":16
    },
    {
        "text":"news",
        "size":16
    },
    {
        "text":"york",
        "size":16
    },
    {
        "text":"emissions",
        "size":15
    },
    {
        "text":"investigation",
        "size":15
    },
    {
        "text":"asked",
        "size":15
    },
    {
        "text":" the",
        "size":15
    },
    {
        "text":"denied",
        "size":15
    },
    {
        "text":"son",
        "size":15
    },
    {
        "text":"make",
        "size":15
    },
    {
        "text":"respond",
        "size":15
    },
    {
        "text":"truck",
        "size":15
    },
    {
        "text":"days",
        "size":15
    },
    {
        "text":"environmental",
        "size":15
    },
    {
        "text":"years",
        "size":14
    },
    {
        "text":"real",
        "size":14
    },
    {
        "text":"hotel",
        "size":14
    },
    {
        "text":"lot",
        "size":14
    },
    {
        "text":"sales",
        "size":14
    },
    {
        "text":"deepwater",
        "size":14
    },
    {
        "text":"foreign",
        "size":14
    },
    {
        "text":"much",
        "size":14
    },
    {
        "text":"take",
        "size":14
    },
    {
        "text":"meeting",
        "size":13
    },
    {
        "text":"known",
        "size":13
    },
    {
        "text":"tennessee",
        "size":13
    },
    {
        "text":"court",
        "size":13
    },
    {
        "text":"jr",
        "size":13
    },
    {
        "text":"state",
        "size":13
    },
    {
        "text":"related",
        "size":13
    },
    {
        "text":"came",
        "size":13
    },
    {
        "text":"least",
        "size":13
    },
    {
        "text":"lawyers",
        "size":13
    },
    {
        "text":"mcdougal",
        "size":13
    },
    {
        "text":"states",
        "size":13
    },
    {
        "text":"units",
        "size":13
    },
    {
        "text":"seeking",
        "size":13
    },
    {
        "text":"comment",
        "size":13
    },
    {
        "text":"think",
        "size":12
    },
    {
        "text":"attorney",
        "size":12
    },
    {
        "text":"back",
        "size":12
    },
    {
        "text":"rule",
        "size":12
    },
    {
        "text":"sex",
        "size":12
    },
    {
        "text":"role",
        "size":12
    },
    {
        "text":"month",
        "size":12
    },
    {
        "text":"delhi",
        "size":12
    },
    {
        "text":"indian",
        "size":12
    },
    {
        "text":"never",
        "size":12
    },
    {
        "text":"owners",
        "size":12
    },
    {
        "text":"recent",
        "size":12
    },
    {
        "text":"golf",
        "size":12
    },
    {
        "text":"pruitt",
        "size":12
    },
    {
        "text":"horizon",
        "size":12
    },
    {
        "text":"saying",
        "size":12
    },
    {
        "text":"financial",
        "size":12
    },
    {
        "text":"family",
        "size":12
    },
    {
        "text":"karen",
        "size":12
    },
    {
        "text":"comments",
        "size":12
    },
    {
        "text":"thursday",
        "size":11
    },
    {
        "text":"person",
        "size":11
    },
    {
        "text":"partners",
        "size":11
    },
    {
        "text":"policy",
        "size":11
    },
    {
        "text":"threatened",
        "size":11
    },
    {
        "text":"paid",
        "size":11
    },
    {
        "text":"subpoena",
        "size":11
    },
    {
        "text":"rules",
        "size":11
    },
    {
        "text":"know",
        "size":11
    },
    {
        "text":"represented",
        "size":11
    },
    {
        "text":"los",
        "size":11
    },
    {
        "text":"private",
        "size":11
    },
    {
        "text":"it s",
        "size":11
    },
    {
        "text":"personal",
        "size":11
    },
    {
        "text":"longtime",
        "size":11
    },
    {
        "text":"weeks",
        "size":11
    },
    {
        "text":60,
        "size":11
    }
]
