var co_occur_blockchain_Tweets =[
    {
        "text":"[blockchain,bitnation]",
        "size":455
    },
    {
        "text":"[crypto,ethereum]",
        "size":302
    },
    {
        "text":"[crypto,tokens]",
        "size":295
    },
    {
        "text":"[crypto,blockchain]",
        "size":295
    },
    {
        "text":"[crypto,coins]",
        "size":290
    },
    {
        "text":"[crypto,predictor]",
        "size":290
    },
    {
        "text":"[crypto,cryptocurrency]",
        "size":290
    },
    {
        "text":"[join,network]",
        "size":284
    },
    {
        "text":"[bitcoin,investor]",
        "size":273
    },
    {
        "text":"[bitcoin,ico]",
        "size":270
    }
]
