var tweet_words_trump = [
    {
        "text":"trump",
        "size":333668
    },
    {
        "text":"stormy",
        "size":259903
    },
    {
        "text":"resistance",
        "size":167397
    },
    {
        "text":"daniels",
        "size":165308
    },
    {
        "text":"news",
        "size":146887
    },
    {
        "text":"real",
        "size":131387
    },
    {
        "text":"maga",
        "size":121785
    },
    {
        "text":"donald",
        "size":99127
    },
    {
        "text":"time",
        "size":79607
    },
    {
        "text":"fox",
        "size":77700
    },
    {
        "text":"president",
        "size":72208
    },
    {
        "text":"trumps",
        "size":63933
    },
    {
        "text":"resist",
        "size":57565
    },
    {
        "text":"potus",
        "size":54301
    },
    {
        "text":"white",
        "size":52041
    },
    {
        "text":"kids",
        "size":51701
    },
    {
        "text":"porn",
        "size":50389
    },
    {
        "text":"moniteau",
        "size":47957
    },
    {
        "text":"may",
        "size":47189
    },
    {
        "text":"give",
        "size":47188
    },
    {
        "text":"david",
        "size":46762
    },
    {
        "text":"gun",
        "size":46708
    },
    {
        "text":"will",
        "size":46430
    },
    {
        "text":"now",
        "size":46173
    },
    {
        "text":"people",
        "size":44722
    },
    {
        "text":"poll",
        "size":44071
    },
    {
        "text":"march",
        "size":43890
    },
    {
        "text":"lm",
        "size":43695
    },
    {
        "text":"jones",
        "size":43695
    },
    {
        "text":"corey",
        "size":43695
    },
    {
        "text":"hogg",
        "size":43625
    },
    {
        "text":"like",
        "size":42989
    },
    {
        "text":"impeach",
        "size":41961
    },
    {
        "text":"wave",
        "size":41898
    },
    {
        "text":"leaders",
        "size":40766
    },
    {
        "text":"respectfully",
        "size":40050
    },
    {
        "text":"candace",
        "size":40050
    },
    {
        "text":"emerge",
        "size":40050
    },
    {
        "text":"star",
        "size":39844
    },
    {
        "text":"de",
        "size":39404
    },
    {
        "text":"us",
        "size":37429
    },
    {
        "text":"just",
        "size":36652
    },
    {
        "text":"amp",
        "size":36256
    },
    {
        "text":"michael",
        "size":36058
    },
    {
        "text":"high",
        "size":35600
    },
    {
        "text":"lives",
        "size":35335
    },
    {
        "text":"think",
        "size":35112
    },
    {
        "text":"school",
        "size":34969
    },
    {
        "text":"voice",
        "size":34635
    },
    {
        "text":"can",
        "size":34595
    },
    {
        "text":"breaking",
        "size":34488
    },
    {
        "text":"russian",
        "size":34048
    },
    {
        "text":"zk",
        "size":33809
    },
    {
        "text":"aeum9s",
        "size":33809
    },
    {
        "text":"sanitynra",
        "size":33809
    },
    {
        "text":"john",
        "size":32998
    },
    {
        "text":"attorney",
        "size":32566
    },
    {
        "text":"vote",
        "size":32241
    },
    {
        "text":"entire",
        "size":32074
    },
    {
        "text":"contingent",
        "size":32074
    },
    {
        "text":"follow",
        "size":31406
    },
    {
        "text":"take",
        "size":31375
    },
    {
        "text":"nancy",
        "size":31057
    },
    {
        "text":"lv",
        "size":31057
    },
    {
        "text":"morningjoe",
        "size":30031
    },
    {
        "text":"retweet",
        "size":29088
    },
    {
        "text":"r",
        "size":28689
    },
    {
        "text":"x",
        "size":28653
    },
    {
        "text":"cohen",
        "size":28043
    },
    {
        "text":"says",
        "size":27265
    },
    {
        "text":"bill",
        "size":27096
    },
    {
        "text":60,
        "size":26950
    },
    {
        "text":"h",
        "size":26809
    },
    {
        "text":"tcot",
        "size":26765
    },
    {
        "text":"mueller",
        "size":26686
    },
    {
        "text":"q",
        "size":26616
    },
    {
        "text":"ej",
        "size":25703
    },
    {
        "text":"suing",
        "size":25488
    },
    {
        "text":"xqr",
        "size":25488
    },
    {
        "text":"h8n",
        "size":25488
    },
    {
        "text":"heres",
        "size":25488
    },
    {
        "text":"hirschberger",
        "size":25394
    },
    {
        "text":"please",
        "size":25386
    },
    {
        "text":"american",
        "size":25030
    },
    {
        "text":"women",
        "size":24903
    },
    {
        "text":"control",
        "size":24727
    },
    {
        "text":"qanon",
        "size":24515
    },
    {
        "text":"want",
        "size":24398
    },
    {
        "text":"cnn",
        "size":24234
    },
    {
        "text":"funds",
        "size":23612
    },
    {
        "text":"protect",
        "size":23612
    },
    {
        "text":"bolton",
        "size":23415
    },
    {
        "text":"omar",
        "size":23327
    },
    {
        "text":"txas",
        "size":22981
    },
    {
        "text":"sandra",
        "size":22981
    },
    {
        "text":"see",
        "size":22915
    },
    {
        "text":"lets",
        "size":22853
    },
    {
        "text":"hillary",
        "size":22760
    },
    {
        "text":"well",
        "size":22661
    },
    {
        "text":"al",
        "size":22534
    },
    {
        "text":"pollsofpolitics",
        "size":22458
    },
    {
        "text":"usa",
        "size":22233
    },
    {
        "text":"back",
        "size":22015
    },
    {
        "text":"friends",
        "size":21753
    },
    {
        "text":"never",
        "size":21667
    },
    {
        "text":"war",
        "size":21650
    },
    {
        "text":"spread",
        "size":21569
    },
    {
        "text":"minutes",
        "size":21244
    },
    {
        "text":"military",
        "size":21089
    },
    {
        "text":"one",
        "size":21086
    },
    {
        "text":"fake",
        "size":21007
    },
    {
        "text":"security",
        "size":20691
    },
    {
        "text":"b",
        "size":20687
    },
    {
        "text":"use",
        "size":20526
    },
    {
        "text":"national",
        "size":20383
    },
    {
        "text":"l",
        "size":20331
    },
    {
        "text":"dont",
        "size":20251
    },
    {
        "text":"foxand",
        "size":20233
    },
    {
        "text":"ann",
        "size":20183
    },
    {
        "text":"russia",
        "size":20179
    },
    {
        "text":"held",
        "size":20133
    },
    {
        "text":"comey",
        "size":19647
    },
    {
        "text":"emolclause",
        "size":19253
    },
    {
        "text":"terrorist",
        "size":19154
    },
    {
        "text":"anon",
        "size":18705
    },
    {
        "text":"today",
        "size":18610
    },
    {
        "text":"diplomats",
        "size":18561
    },
    {
        "text":"betrayed",
        "size":18515
    },
    {
        "text":"mateen",
        "size":18515
    },
    {
        "text":"coincidentally",
        "size":18515
    },
    {
        "text":"group",
        "size":18515
    },
    {
        "text":"member",
        "size":18515
    },
    {
        "text":"qaeda",
        "size":18515
    },
    {
        "text":"w",
        "size":18338
    },
    {
        "text":"amendment",
        "size":18073
    },
    {
        "text":"kwilli1046",
        "size":17942
    },
    {
        "text":"remember",
        "size":17908
    },
    {
        "text":"way",
        "size":17843
    },
    {
        "text":"fr",
        "size":17818
    },
    {
        "text":"mc",
        "size":17739
    },
    {
        "text":"ccot",
        "size":17666
    },
    {
        "text":"tru",
        "size":17563
    },
    {
        "text":"million",
        "size":17392
    },
    {
        "text":"la",
        "size":17324
    },
    {
        "text":"using",
        "size":17291
    },
    {
        "text":"keep",
        "size":17110
    },
    {
        "text":"need",
        "size":17091
    },
    {
        "text":"parenthood",
        "size":17077
    },
    {
        "text":"planned",
        "size":17077
    },
    {
        "text":"campaign",
        "size":16896
    },
    {
        "text":533,
        "size":16843
    },
    {
        "text":"schools",
        "size":16843
    },
    {
        "text":"guards",
        "size":16843
    },
    {
        "text":"armed",
        "size":16843
    },
    {
        "text":"given",
        "size":16843
    },
    {
        "text":"best",
        "size":16761
    },
    {
        "text":"second",
        "size":16641
    },
    {
        "text":"p",
        "size":16521
    },
    {
        "text":"des",
        "size":16458
    },
    {
        "text":"issue",
        "size":16046
    },
    {
        "text":"much",
        "size":15874
    },
    {
        "text":"approve",
        "size":15853
    },
    {
        "text":"repeal",
        "size":15754
    },
    {
        "text":"tombx7m",
        "size":15615
    },
    {
        "text":"trumptweets2020",
        "size":15411
    },
    {
        "text":"evangelicals",
        "size":15397
    },
    {
        "text":"say",
        "size":15389
    },
    {
        "text":"day",
        "size":15361
    },
    {
        "text":"borderwall",
        "size":15113
    },
    {
        "text":"know",
        "size":15096
    },
    {
        "text":"dear",
        "size":15094
    },
    {
        "text":"built",
        "size":15029
    },
    {
        "text":"u",
        "size":15022
    },
    {
        "text":"da",
        "size":15021
    },
    {
        "text":"ostroy",
        "size":14800
    },
    {
        "text":"andy",
        "size":14800
    },
    {
        "text":"men",
        "size":14597
    },
    {
        "text":"fire",
        "size":14511
    },
    {
        "text":"putin",
        "size":14468
    },
    {
        "text":"shanne",
        "size":14393
    },
    {
        "text":"stokes",
        "size":14393
    },
    {
        "text":"m",
        "size":14065
    },
    {
        "text":"years",
        "size":14047
    },
    {
        "text":"go",
        "size":13993
    },
    {
        "text":"god",
        "size":13969
    },
    {
        "text":"swamp",
        "size":13949
    },
    {
        "text":"census",
        "size":13941
    },
    {
        "text":"even",
        "size":13850
    },
    {
        "text":"get",
        "size":13837
    },
    {
        "text":"everyone",
        "size":13818
    },
    {
        "text":"trum",
        "size":13808
    },
    {
        "text":"pay",
        "size":13798
    },
    {
        "text":"team",
        "size":13769
    },
    {
        "text":"year",
        "size":13551
    },
    {
        "text":"world",
        "size":13543
    },
    {
        "text":"vot",
        "size":13496
    },
    {
        "text":"parkland",
        "size":13477
    },
    {
        "text":"picture",
        "size":13244
    },
    {
        "text":"coulter",
        "size":13193
    },
    {
        "text":"must",
        "size":13162
    },
    {
        "text":"getting",
        "size":13090
    },
    {
        "text":"gop",
        "size":13012
    },
    {
        "text":"j",
        "size":12949
    },
    {
        "text":"house",
        "size":12899
    },
    {
        "text":"budget",
        "size":12893
    },
    {
        "text":"wall",
        "size":12864
    },
    {
        "text":"former",
        "size":12769
    },
    {
        "text":"build",
        "size":12748
    },
    {
        "text":"le",
        "size":12729
    },
    {
        "text":"first",
        "size":12563
    },
    {
        "text":"alone",
        "size":12535
    },
    {
        "text":"aunt",
        "size":12433
    },
    {
        "text":"crabby",
        "size":12433
    },
    {
        "text":"monday",
        "size":12429
    },
    {
        "text":"accuses",
        "size":12323
    },
    {
        "text":"survivors",
        "size":12276
    },
    {
        "text":"currently",
        "size":12232
    },
    {
        "text":"called",
        "size":12218
    },
    {
        "text":"mattis",
        "size":12205
    },
    {
        "text":"show",
        "size":12078
    },
    {
        "text":"hunter",
        "size":12000
    },
    {
        "text":"congress",
        "size":11862
    },
    {
        "text":"america",
        "size":11851
    },
    {
        "text":"main",
        "size":11796
    },
    {
        "text":"better",
        "size":11747
    },
    {
        "text":"trade",
        "size":11741
    },
    {
        "text":"laws",
        "size":11736
    },
    {
        "text":"tuesday",
        "size":11730
    },
    {
        "text":"country",
        "size":11706
    },
    {
        "text":"without",
        "size":11664
    },
    {
        "text":"babies",
        "size":11621
    },
    {
        "text":"allowance",
        "size":11621
    },
    {
        "text":"killing",
        "size":11621
    },
    {
        "text":"restrooms",
        "size":11621
    },
    {
        "text":"advocate",
        "size":11621
    },
    {
        "text":"bashing",
        "size":11621
    },
    {
        "text":"y",
        "size":11589
    },
    {
        "text":"drunk",
        "size":11450
    },
    {
        "text":"texas",
        "size":11420
    },
    {
        "text":"big",
        "size":11380
    },
    {
        "text":"citizenship",
        "size":11341
    },
    {
        "text":"senator",
        "size":11264
    },
    {
        "text":"christian",
        "size":11236
    },
    {
        "text":"colleges",
        "size":11179
    },
    {
        "text":"isnt",
        "size":11148
    },
    {
        "text":"supporters",
        "size":11071
    },
    {
        "text":"good",
        "size":11062
    },
    {
        "text":"question",
        "size":11034
    },
    {
        "text":"thoughts",
        "size":11031
    },
    {
        "text":"money",
        "size":11024
    },
    {
        "text":"necessarily",
        "size":11000
    },
    {
        "text":"sane",
        "size":11000
    }
]
