var co_occur_trump_Tweets =[
    {
        "text":"[daniels,film]",
        "size":70
    },
    {
        "text":"[daniels,stormy]",
        "size":65
    },
    {
        "text":"[donald,suing]",
        "size":64
    },
    {
        "text":"[donald,president]",
        "size":62
    },
    {
        "text":"[daniels,suing]",
        "size":56
    },
    {
        "text":"[trump,affair]",
        "size":46
    },
    {
        "text":"[daniels,adult]",
        "size":40
    },
    {
        "text":"[daniels,trumps]",
        "size":36
    },
    {
        "text":"[daniels,president]",
        "size":34
    },
    {
        "text":"[daniels,star]",
        "size":67
    }
]
