var tweet_words_blockchain = [
    {
        "text":"blockchain",
        "size":235212
    },
    {
        "text":"crypto",
        "size":152761
    },
    {
        "text":"bitcoin",
        "size":92108
    },
    {
        "text":"currency",
        "size":67080
    },
    {
        "text":"airdrop",
        "size":66263
    },
    {
        "text":"token",
        "size":61773
    },
    {
        "text":"ambit",
        "size":59035
    },
    {
        "text":"join",
        "size":57985
    },
    {
        "text":"mining",
        "size":49086
    },
    {
        "text":"cool",
        "size":44608
    },
    {
        "text":"ethereum",
        "size":38342
    },
    {
        "text":"tokens",
        "size":38187
    },
    {
        "text":"platform",
        "size":35690
    },
    {
        "text":"cousin",
        "size":33999
    },
    {
        "text":"april",
        "size":33664
    },
    {
        "text":"price",
        "size":32820
    },
    {
        "text":"sale",
        "size":31545
    },
    {
        "text":"amp",
        "size":30627
    },
    {
        "text":"systems",
        "size":29966
    },
    {
        "text":"eth",
        "size":28985
    },
    {
        "text":"btc",
        "size":28854
    },
    {
        "text":"days",
        "size":28801
    },
    {
        "text":"coin",
        "size":28680
    },
    {
        "text":"plaza",
        "size":28529
    },
    {
        "text":"network",
        "size":27811
    },
    {
        "text":"read",
        "size":27678
    },
    {
        "text":"now",
        "size":27510
    },
    {
        "text":"miss",
        "size":27474
    },
    {
        "text":"data",
        "size":27009
    },
    {
        "text":"bank",
        "size":26983
    },
    {
        "text":"left",
        "size":26247
    },
    {
        "text":"find",
        "size":24862
    },
    {
        "text":"presale",
        "size":24685
    },
    {
        "text":"one",
        "size":24561
    },
    {
        "text":"dont",
        "size":22613
    },
    {
        "text":"bethereumteam",
        "size":22500
    },
    {
        "text":"telegram",
        "size":21950
    },
    {
        "text":"preico",
        "size":21303
    },
    {
        "text":"first",
        "size":20947
    },
    {
        "text":"bonus",
        "size":20626
    },
    {
        "text":"know",
        "size":20291
    },
    {
        "text":"world",
        "size":19826
    },
    {
        "text":"project",
        "size":19437
    },
    {
        "text":"satoshi",
        "size":19209
    },
    {
        "text":"technology",
        "size":19032
    },
    {
        "text":"swapy",
        "size":18438
    },
    {
        "text":"live",
        "size":17953
    },
    {
        "text":"exchanges",
        "size":17848
    },
    {
        "text":"ceo",
        "size":17804
    },
    {
        "text":"future",
        "size":17724
    },
    {
        "text":"news",
        "size":17717
    },
    {
        "text":"free",
        "size":17671
    },
    {
        "text":"happy",
        "size":17601
    },
    {
        "text":"money",
        "size":17258
    },
    {
        "text":"earn",
        "size":17166
    },
    {
        "text":"coming",
        "size":17062
    },
    {
        "text":"take",
        "size":16898
    },
    {
        "text":"can",
        "size":16860
    },
    {
        "text":"top",
        "size":16089
    },
    {
        "text":"swachhcoin",
        "size":15921
    },
    {
        "text":"coins",
        "size":15815
    },
    {
        "text":"bit",
        "size":15789
    },
    {
        "text":"website",
        "size":15686
    },
    {
        "text":"great",
        "size":15520
    },
    {
        "text":"easter",
        "size":15514
    },
    {
        "text":"travel",
        "size":15422
    },
    {
        "text":"details",
        "size":15375
    },
    {
        "text":"airdropping",
        "size":15366
    },
    {
        "text":"use",
        "size":14620
    },
    {
        "text":"based",
        "size":14467
    },
    {
        "text":"robotina",
        "size":14237
    },
    {
        "text":"pre",
        "size":14152
    },
    {
        "text":"chain",
        "size":14038
    },
    {
        "text":"inc",
        "size":13754
    },
    {
        "text":"together",
        "size":13618
    },
    {
        "text":"d",
        "size":13575
    },
    {
        "text":"info",
        "size":13452
    },
    {
        "text":"market",
        "size":13400
    },
    {
        "text":"social",
        "size":13342
    },
    {
        "text":"app",
        "size":13320
    },
    {
        "text":"cloud",
        "size":13315
    },
    {
        "text":"look",
        "size":13228
    },
    {
        "text":"bethereum",
        "size":13206
    },
    {
        "text":"lets",
        "size":13195
    },
    {
        "text":"adosia",
        "size":13194
    },
    {
        "text":"tihosay",
        "size":13044
    },
    {
        "text":2000,
        "size":12920
    },
    {
        "text":"tech",
        "size":12903
    },
    {
        "text":"starts",
        "size":12883
    },
    {
        "text":"tokensale",
        "size":12876
    },
    {
        "text":"follow",
        "size":12794
    },
    {
        "text":"travelapp",
        "size":12784
    },
    {
        "text":"cuz",
        "size":12773
    },
    {
        "text":"nbt",
        "size":12680
    },
    {
        "text":"noble",
        "size":12680
    },
    {
        "text":60000,
        "size":12680
    },
    {
        "text":"subscribers",
        "size":12680
    },
    {
        "text":"trading",
        "size":12607
    },
    {
        "text":"participate",
        "size":12539
    },
    {
        "text":"wallet",
        "size":12490
    },
    {
        "text":"et",
        "size":12458
    },
    {
        "text":"partnership",
        "size":12339
    },
    {
        "text":"invest",
        "size":12284
    },
    {
        "text":"ai",
        "size":12276
    },
    {
        "text":"go",
        "size":12159
    },
    {
        "text":"wish",
        "size":12113
    },
    {
        "text":"o",
        "size":11990
    },
    {
        "text":"airdrops",
        "size":11965
    },
    {
        "text":"announces",
        "size":11878
    },
    {
        "text":"build",
        "size":11866
    },
    {
        "text":"european",
        "size":11806
    },
    {
        "text":"round",
        "size":11778
    },
    {
        "text":"purchase",
        "size":11615
    },
    {
        "text":"y",
        "size":11607
    },
    {
        "text":"soon",
        "size":11462
    },
    {
        "text":"team",
        "size":11426
    },
    {
        "text":"toke",
        "size":11388
    },
    {
        "text":"obq",
        "size":11336
    },
    {
        "text":"traveltech",
        "size":11336
    },
    {
        "text":"uroq",
        "size":11336
    },
    {
        "text":"private",
        "size":11265
    },
    {
        "text":"noblebit3",
        "size":11238
    },
    {
        "text":"btfproject",
        "size":11213
    },
    {
        "text":"via",
        "size":11158
    },
    {
        "text":"good",
        "size":11015
    },
    {
        "text":"price",
        "size":10998
    },
    {
        "text":"smart",
        "size":10963
    },
    {
        "text":"role",
        "size":10943
    },
    {
        "text":"ic",
        "size":10844
    },
    {
        "text":"article",
        "size":10702
    },
    {
        "text":"cash",
        "size":10622
    },
    {
        "text":"start",
        "size":10536
    },
    {
        "text":"help",
        "size":10493
    },
    {
        "text":"russian",
        "size":10464
    },
    {
        "text":"experience",
        "size":10414
    },
    {
        "text":"review",
        "size":10401
    },
    {
        "text":"wire",
        "size":10400
    },
    {
        "text":"holliday",
        "size":10304
    },
    {
        "text":"futureeuropean",
        "size":10304
    },
    {
        "text":"consumers",
        "size":10302
    },
    {
        "text":"solved",
        "size":10263
    },
    {
        "text":"id",
        "size":10258
    },
    {
        "text":"just",
        "size":10203
    },
    {
        "text":"fintech",
        "size":10143
    },
    {
        "text":"day",
        "size":10142
    },
    {
        "text":"advantage",
        "size":10098
    },
    {
        "text":"means",
        "size":10078
    },
    {
        "text":"wealth",
        "size":9843
    },
    {
        "text":"supply",
        "size":9809
    },
    {
        "text":"nodepowereu",
        "size":9787
    },
    {
        "text":"cryptocurrencies",
        "size":9751
    },
    {
        "text":"opportun",
        "size":9675
    },
    {
        "text":"final",
        "size":9675
    },
    {
        "text":"million",
        "size":9478
    },
    {
        "text":"already",
        "size":9472
    },
    {
        "text":"community",
        "size":9447
    },
    {
        "text":"founder",
        "size":9413
    },
    {
        "text":"digital",
        "size":9399
    },
    {
        "text":"create",
        "size":9394
    },
    {
        "text":"dragon",
        "size":9308
    },
    {
        "text":"w",
        "size":9269
    },
    {
        "text":"lb",
        "size":9219
    },
    {
        "text":"amicorum",
        "size":9188
    },
    {
        "text":"stratai",
        "size":9090
    },
    {
        "text":"check",
        "size":9002
    },
    {
        "text":"synix",
        "size":8931
    },
    {
        "text":"mlny",
        "size":8898
    },
    {
        "text":"randolph",
        "size":8898
    },
    {
        "text":"ether",
        "size":8864
    },
    {
        "text":"mossland",
        "size":8832
    },
    {
        "text":"total",
        "size":8805
    },
    {
        "text":5,
        "size":8647
    },
    {
        "text":"comment",
        "size":8624
    },
    {
        "text":"iot",
        "size":8608
    },
    {
        "text":"usd",
        "size":8592
    },
    {
        "text":"btf",
        "size":8574
    },
    {
        "text":"peer",
        "size":8496
    },
    {
        "text":"x",
        "size":8485
    },
    {
        "text":"velix",
        "size":8482
    },
    {
        "text":"mobile",
        "size":8381
    },
    {
        "text":"run",
        "size":8344
    },
    {
        "text":"ecosystem",
        "size":8309
    },
    {
        "text":"everyone",
        "size":8289
    },
    {
        "text":"exchange",
        "size":8231
    },
    {
        "text":"win",
        "size":8105
    },
    {
        "text":"thread",
        "size":8066
    },
    {
        "text":"hq",
        "size":8038
    },
    {
        "text":"simply",
        "size":8038
    },
    {
        "text":"vital",
        "size":8038
    },
    {
        "text":"business",
        "size":7921
    },
    {
        "text":"web",
        "size":7905
    },
    {
        "text":"personalized",
        "size":7905
    },
    {
        "text":"health",
        "size":7856
    },
    {
        "text":"gold",
        "size":7814
    },
    {
        "text":"goldgg",
        "size":7814
    },
    {
        "text":"sportsbetting",
        "size":7814
    },
    {
        "text":"become",
        "size":7694
    },
    {
        "text":"blo",
        "size":7660
    },
    {
        "text":"liberty",
        "size":7614
    },
    {
        "text":"journey",
        "size":7583
    },
    {
        "text":"big",
        "size":7455
    },
    {
        "text":"game",
        "size":7437
    },
    {
        "text":"tennessee",
        "size":7396
    },
    {
        "text":"gn",
        "size":7342
    },
    {
        "text":"checkout",
        "size":7342
    },
    {
        "text":"problem",
        "size":7287
    },
    {
        "text":"like",
        "size":7284
    },
    {
        "text":"scientist",
        "size":7257
    },
    {
        "text":"going",
        "size":7246
    },
    {
        "text":"way",
        "size":7221
    },
    {
        "text":"economy",
        "size":7172
    },
    {
        "text":"startup",
        "size":7144
    },
    {
        "text":"analytics",
        "size":7142
    },
    {
        "text":"started",
        "size":7111
    },
    {
        "text":"using",
        "size":7038
    },
    {
        "text":"announcement",
        "size":7033
    },
    {
        "text":"innovative",
        "size":6986
    },
    {
        "text":"2nd",
        "size":6975
    },
    {
        "text":"local",
        "size":6919
    },
    {
        "text":"bounty",
        "size":6915
    },
    {
        "text":"public",
        "size":6908
    },
    {
        "text":"contest",
        "size":6890
    },
    {
        "text":"weeks",
        "size":6859
    },
    {
        "text":"sold",
        "size":6779
    },
    {
        "text":"opportunity",
        "size":6769
    },
    {
        "text":"part",
        "size":6760
    },
    {
        "text":"open",
        "size":6733
    },
    {
        "text":"followers",
        "size":6714
    },
    {
        "text":"created",
        "size":6684
    },
    {
        "text":"garden",
        "size":6618
    }
]
